apiVersion: v1
kind: ServiceAccount
metadata:
  name: stagelog-backend-sa
  namespace: dev-backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::430118823715:role/stagelog-backend-workload-role
