apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stagelog-public-api
  namespace: dev-monolith
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/group.name: stagelog-public-api
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - path: /api/users/
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - path: /prod/api/users
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - path: /prod/api/users/
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - path: /api/events
        pathType: Prefix
        backend:
          service:
            name: events-svc
            port:
              number: 8000
      - path: /api/events/
        pathType: Prefix
        backend:
          service:
            name: events-svc
            port:
              number: 8000
      - path: /prod/api/events
        pathType: Prefix
        backend:
          service:
            name: events-svc
            port:
              number: 8000
      - path: /prod/api/events/
        pathType: Prefix
        backend:
          service:
            name: events-svc
            port:
              number: 8000
      - path: /api/bookmarks
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - path: /api/bookmarks/
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - path: /prod/api/bookmarks
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - path: /prod/api/bookmarks/
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 8000
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: core-svc
            port:
              number: 8000
      - path: /prod/api/
        pathType: Prefix
        backend:
          service:
            name: core-svc
            port:
              number: 8000
